version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
    groups:
      minor-and-patch-version-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      minor-and-patch-security-updates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      include:
        - "*"